import type { TemplateSchema } from '../types/template';

export const defaultTemplateSchema: TemplateSchema = {
  id: 'default-1',
  name: 'Mẫu hóa đơn mới',
  version: '1.0',
  paperSize: 'A4',
  orientation: 'portrait',
  margins: {
    top: 20,
    right: 20,
    bottom: 20,
    left: 20,
  },
  primaryColor: '#1E88E5',
  blocks: [
    {
      type: 'header',
      id: 'header-1',
      visible: true,
      layout: 'logo-center',
      showLogo: false,
      showCompanyName: true,
      showAddress: true,
      showPhone: true,
      showEmail: true,
      showTaxCode: true,
      style: {
        marginBottom: 20,
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#1E88E5',
      },
    },
    {
      type: 'invoice-title',
      id: 'title-1',
      visible: true,
      title: 'HÓA ĐƠN BÁN HÀNG',
      showInvoiceCode: true,
      showBorder: true,
      style: {
        marginTop: 20,
        marginBottom: 20,
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    },
    {
      type: 'invoice-meta',
      id: 'meta-1',
      visible: true,
      showCreatedDate: true,
      showDueDate: true,
      showSalesperson: false,
      layout: 'two-columns',
      style: {
        marginBottom: 20,
      },
    },
    {
      type: 'customer-info',
      id: 'customer-1',
      visible: true,
      showName: true,
      showAddress: true,
      showPhone: true,
      showTaxCode: false,
      style: {
        marginBottom: 20,
      },
    },
    {
      type: 'items-table',
      id: 'items-1',
      visible: true,
      columns: {
        stt: true,
        name: true,
        unit: true,
        quantity: true,
        price: true,
        discount: false,
        tax: false,
        amount: true,
      },
      showHeader: true,
      showBorders: true,
      headerColor: '#1E88E5',
      headerTextColor: '#ffffff',
      style: {
        marginTop: 20,
        marginBottom: 20,
      },
    },
    {
      type: 'totals',
      id: 'totals-1',
      visible: true,
      align: 'right',
      showSubtotal: true,
      showDiscount: false,
      showTax: false,
      showShipping: false,
      showGrandTotal: true,
      showPaid: true,
      showRemaining: true,
      showInWords: false,
      width: 300,
      style: {
        marginTop: 30,
      },
    },
    {
      type: 'signature',
      id: 'signature-1',
      visible: true,
      showSellerSignature: true,
      showCustomerSignature: true,
      layout: 'two-columns',
      style: {
        marginTop: 50,
      },
    },
    {
      type: 'footer',
      id: 'footer-1',
      visible: true,
      showThankYou: true,
      showTerms: false,
      style: {
        marginTop: 30,
        textAlign: 'center',
      },
    },
  ],
};

export const sampleData = {
  // Company
  Ten_Cong_Ty: 'CỬA HÀNG VLXD XƯƠNG LUÂN',
  Dia_Chi_Cong_Ty: '123 Đường Võ Văn Tần, Quận 3, TP.HCM',
  So_Dien_Thoai_Cong_Ty: '028 1234 5678',
  Email_Cong_Ty: 'info@vlxdxuonglan.vn',
  Ma_So_Thue_Cong_Ty: '0123456789',
  
  // Customer
  Khach_Hang: 'Anh Hòa Q.1',
  So_Dien_Thoai: '0901 234 567',
  Dia_Chi_Khach_Hang: '456 Đường Lê Lợi, Quận 1, TP.HCM',
  Ma_So_Thue_Khach: '0987654321',
  
  // Invoice
  Ma_Hoa_Don: 'HD-001',
  Ngay_Tao: '24/02/2026',
  Ngay_Den_Han: '26/03/2026',
  
  // Amounts
  Tong_Tien: '45.200.000₫',
  Chiet_Khau: '0₫',
  Thue: '0₫',
  Phi_Van_Chuyen: '0₫',
  Tong_Cong: '45.200.000₫',
  Da_Thanh_Toan: '30.000.000₫',
  Con_Lai: '15.200.000₫',
  Tien_Bang_Chu: 'Bốn mươi lăm triệu hai trăm nghìn đồng',
  
  // Items
  items: [
    {
      STT: '1',
      Ten_Hang: 'Gạch Đồng Tâm 60x60',
      Don_Vi: 'Viên',
      So_Luong: '200',
      Don_Gia: '80.000₫',
      Chiet_Khau: '0₫',
      Thue: '0₫',
      Thanh_Tien: '16.000.000₫',
    },
    {
      STT: '2',
      Ten_Hang: 'Xi măng Hà Tiên PCB40',
      Don_Vi: 'Bao',
      So_Luong: '100',
      Don_Gia: '120.000₫',
      Chiet_Khau: '0₫',
      Thue: '0₫',
      Thanh_Tien: '12.000.000₫',
    },
    {
      STT: '3',
      Ten_Hang: 'Cát vàng xây dựng',
      Don_Vi: 'Khối',
      So_Luong: '5',
      Don_Gia: '600.000₫',
      Chiet_Khau: '0₫',
      Thue: '0₫',
      Thanh_Tien: '3.000.000₫',
    },
    {
      STT: '4',
      Ten_Hang: 'Sắt thép Hòa Phát D10',
      Don_Vi: 'Kg',
      So_Luong: '500',
      Don_Gia: '28.400₫',
      Chiet_Khau: '0₫',
      Thue: '0₫',
      Thanh_Tien: '14.200.000₫',
    },
  ],
};
